import type { Metadata } from "next";
import AppHeader from "@/components/mainLayout/Header/AppHeader";
import AppNav from "@/components/mainLayout/Nav/AppNav";
import styles from "./layout.module.css"; // Create this CSS module

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={styles.layoutContainer}>
      <AppHeader />
      <main className={styles.mainContent}>{children}</main>
      <AppNav />
    </div>
  );
}