import type { Metadata } from "next";
import AppHeader from "@/components/mainLayout/Header/AppHeader";
import AppNav from "@/components/mainLayout/Nav/AppNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <AppHeader />
      <main>{children}</main>
      <AppNav />
    </>
  );
}
