version: '3.7'
services:
  web:
    image: .
    container_name: nextjs-hospital-bicis
    ports:
      - 3000:3000
    environment:
      NEXT_PUBLIC_APPWRITE_PROJECT_ID: ${NEXT_PUBLIC_APPWRITE_PROJECT_ID}
      NEXT_PUBLIC_APPWRITE_ENDPOINT: ${NEXT_PUBLIC_APPWRITE_ENDPOINT}
      NEXT_APPWRITE_API_KEY: ${NEXT_APPWRITE_API_KEY}
      NEXT_PUBLIC_APPWRITE_DATABASE_ID: ${NEXT_PUBLIC_APPWRITE_DATABASE_ID}
      NEXT_PUBLIC_APPWRITE_COLLECTION_ID: ${NEXT_PUBLIC_APPWRITE_COLLECTION_ID}
      NEXT_PUBLIC_APPWRITE_RESERVATIONS_COLLECTION_ID: ${NEXT_PUBLIC_APPWRITE_RESERVATIONS_COLLECTION_ID}
      NEXT_PUBLIC_ALLOWED_EMAIL_DOMAIN: ${NEXT_PUBLIC_ALLOWED_EMAIL_DOMAIN}
      NEXT_PUBLIC_APPWRITE_BUCKET_ID: ${NEXT_PUBLIC_APPWRITE_BUCKET_ID}
