name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Add commit message as image description
      run: |
        COMMIT_MESSAGE=$(git log -1 --pretty=%B)
        echo "Description: $COMMIT_MESSAGE" > description.txt
        docker build . --file Dockerfile --tag ghcr.io/${{ github.repository_owner }}/hospital-bicis-web:${{ github.sha }} --label "description=$COMMIT_MESSAGE"
    - name: Tag the image as latest
      run: docker tag ghcr.io/${{ github.repository_owner }}/hospital-bicis-web:${{ github.sha }} ghcr.io/${{ github.repository_owner }}/hospital-bicis-web:latest
    - name: Push the Docker image with SHA tag
      run: docker push ghcr.io/${{ github.repository_owner }}/hospital-bicis-web:${{ github.sha }}
    - name: Push the Docker image with latest tag
      run: docker push ghcr.io/${{ github.repository_owner }}/hospital-bicis-web:latest